# Generated by Django 4.0.6 on 2022-07-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('cuil_t', models.IntegerField(help_text='Cuil o cuit sin guiones', null=True, verbose_name='Cuil_t')),
                ('telefono', models.IntegerField(max_length=13, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha de emicion', verbose_name='Fecha')),
                ('importe', models.IntegerField(max_length=100, verbose_name='Importe')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasVentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='fecha de emision', verbose_name='Fecha')),
                ('Cantidad', models.IntegerField(max_length=10, verbose_name='Cantidad')),
                ('Importe', models.IntegerField(max_length=100, verbose_name='Importe')),
                ('idCliente', models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idFactura', models.ForeignKey(help_text='Factura', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.facturascompras')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la prenda detallada', max_length=30, verbose_name='Nombre')),
                ('talleN', models.IntegerField(help_text='Talle en numero', max_length=10, null=True, verbose_name='Talle Numero')),
                ('talleL', models.CharField(blank=True, help_text='Talle en letra', max_length=4, verbose_name='Talle Letra')),
                ('stock', models.IntegerField(max_length=6, verbose_name='Stock')),
                ('categoria', models.CharField(help_text='Tipo de prenda', max_length=20)),
                ('precio', models.IntegerField(max_length=6, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre', max_length=20, verbose_name='Nombre')),
                ('cuil_t', models.IntegerField(help_text='Cuil o cuit sin guiones', verbose_name='Cuil_t')),
                ('direccion', models.CharField(help_text='Calle y numero', max_length=40, verbose_name='Direccion')),
                ('localidad', models.CharField(max_length=20, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=20, verbose_name='Cordoba')),
                ('cp', models.IntegerField(help_text='Codigo postal', verbose_name='CP')),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idFactura', models.ForeignKey(help_text='Factura', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.facturasventas')),
            ],
        ),
        migrations.CreateModel(
            name='Remitos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha de emicion')),
                ('importe', models.IntegerField(max_length=100, verbose_name='Importe')),
                ('idFactura', models.ForeignKey(help_text='Factura', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.facturascompras')),
                ('idProveedor', models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosPedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idPedido', models.ForeignKey(help_text='Pedido', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.pedidos')),
                ('idProducto', models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.productos')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SyMApp.productos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='idProveedor',
            field=models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.proveedores'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='idRemito',
            field=models.ForeignKey(help_text='Remito', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.remitos'),
        ),
        migrations.CreateModel(
            name='PagoProveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField(help_text='Fecha de pago', verbose_name='Fecha pago')),
                ('idFactura', models.ForeignKey(help_text='Factura', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.facturascompras')),
            ],
        ),
        migrations.AddField(
            model_name='facturasventas',
            name='idProducto',
            field=models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.productos'),
        ),
        migrations.AddField(
            model_name='facturascompras',
            name='idProducto',
            field=models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.productos'),
        ),
        migrations.AddField(
            model_name='facturascompras',
            name='idProveedor',
            field=models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.proveedores'),
        ),
    ]
