# Generated by Django 4.0.6 on 2022-07-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SyMApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remitos',
            name='idFactura',
        ),
        migrations.RemoveField(
            model_name='remitos',
            name='idProveedor',
        ),
        migrations.RemoveField(
            model_name='pagoproveedores',
            name='idFactura',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='idFactura',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='idRemito',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='idProducto',
            field=models.ForeignKey(help_text='Productos', on_delete=django.db.models.deletion.CASCADE, to='SyMApp.productos'),
        ),
        migrations.DeleteModel(
            name='FacturasCompras',
        ),
        migrations.DeleteModel(
            name='Remitos',
        ),
    ]
